### ISSUE TITLE
Progress not working on local html files loaded with loadRequest:

### ISSUE THREAD

**Issue by imanzarrabian** [ninjinkun/NJKWebViewProgress#40]
Hey, 
It seems to me that only http and https schemes are currently supported and this makes urls starting with file:// not work with the progress mechanism. Am I correct or missing something? 
This could be useful for local HTML strings for example. Using a file instead of loadHTMLString:
Anyway I added this line of code and a pull request ready if needed ;)
```
BOOL isHTTPOrLocalFile = [request.URL.scheme isEqualToString:@"http"] || [request.URL.scheme isEqualToString:@"https"] || [request.URL.scheme isEqualToString:@"file"];
```

**Comment by axl411** [comment]
@ninjinkun hi 人参君, could you please add a new release including this PR? Currently the newest release is "on May 7, 2014"
